sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- webpack --progress
after_success:
# Build Docker Images
- docker build -t cloudboost/file-ui:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/file-ui:latest .
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=2.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITLOGIN@github.com/CloudBoost/file-ui --tags
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "README.md"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
after_deploy:
# Docker Deploy.
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
  docker push cloudboost/file-ui:2.0.$TRAVIS_BUILD_NUMBER;
  docker push cloudboost/file-ui:latest;
  fi
branches:
  except:
    - /^*-v[0-9]/
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW
